version: '3.8'
services: 
    api-service:
        build: .
        volumes: 
            - .:/usr/src/app/
            # - /home/yongfu/fasttext-cc.zh.300.bin:/usr/src/app/fasttext-cc.zh.300.bin
        ports: 
            - 5000:5000
        environment: 
            PORT: 5000
            FLASK_DEBUG: 1
